Vectors
ChrisO345/furthermaths-module pull request #8
Opened 2022-10-23 14:20 UTC by ashu0x

2022-10-23 16:08 UTC, ChrisO345 commented
Could you add this to the specified dot_product.py file

2022-10-23 16:40 UTC, ashu0x commented
Can you recheck?

2022-10-26 04:55 UTC, ashu0x commented
Done

2022-10-26 05:17 UTC, ChrisO345 requested changes

2022-10-26 06:47 UTC, merged